<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TYSS-MF-029" name="Default test" tests="1" failures="1" timestamp="17 Aug 2017 15:57:36 GMT" time="26.128" errors="0">
  <testcase name="testMeasurementofLength" time="7.385" classname="com.pearsonebook.testscripts.EbookTest">
    <failure type="org.sikuli.script.FindFailed" message="can not find D:\Pearson Poc scripts\pearsonebook\src\test\resources\ebookImages\mathematics.PNG on the screen.">
      <![CDATA[FindFailed: can not find D:\Pearson Poc scripts\pearsonebook\src\test\resources\ebookImages\mathematics.PNG on the screen.
  Line 1574, in file Region.java

	at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
	at org.sikuli.script.Region.wait(Region.java:1682)
	at org.sikuli.script.Region.find(Region.java:1590)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:1991)
	at org.sikuli.script.Region.click(Region.java:2197)
	at org.sikuli.script.Region.click(Region.java:2181)
	at com.pearsonebook.testscripts.EbookTest.testMeasurementofLength(EbookTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testMeasurementofLength -->
</testsuite> <!-- Default test -->
